# Generated by Django 4.1.2 on 2022-11-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_seat_nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_stand_nr',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Concerts', 'Concerts'), ('Cinema', 'Cinema'), ('Sport', 'Sport'), ('Theaters', 'Theaters')], default='Cinema', max_length=200),
        ),
    ]
