# Generated by Django 4.1.2 on 2022-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_price_event_ticket_seat_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Bály', 'Bály a taneční akce'), ('Divadla', 'Divadelní představení'), ('Kina', 'Kina'), ('Koncerty', 'Koncerty'), ('Sport', 'Sportovní akce'), ('Veletrhy', 'Veletrhy'), ('Vernisáže', 'Vernisáže'), ('Výstavy', 'Výstavy'), ('Zábavy', 'Zábavy')], default='Koncerty', max_length=200),
        ),
    ]
